version: "3.7"

services:
  database: #ESSE É O NOME DO SERVICE QUE DEVE ESTAR NO ARQUIVO DE CRIAÇÃO DE CONEXÃO
    image: postgres
    container_name: database_todo
    restart: always
    ports: 
      - 5432:5432
    environment:
      - POSTGRES_USER=${PG_USER}
      - POSTGRES_PASSWORD=${PG_PASSWORD}
      - POSTGRES_DB=${PG_DATABASE}
    volumes:
      - pgdata:/data/postgres


  app:
    stdin_open: true
    build:
      context: .
      dockerfile: Dockerfile
    container_name: todo-app
    restart: always
    ports: 
      - 3333:3333
      - 9229:9229 #Você pode inserir essa porta tbm pra poder usar o debug
    volumes: 
      - .:/usr/app
      - /usr/src/app/node_modules
    depends_on:
      - database

volumes:
  pgdata:
    driver: local